% PARX
%
% Files
%   lastdir            - d = lastdir(p)
%   parx2an            - parx2an(scandir)
%   parx2tiff          - parx2tiff(rootdir)
%   parxacqmeth        - acqmeth = parxacqmeth(scandir)
%   parxacqtime        - t = parxacqtime(acqstr)
%   parxdatenum        - mdn = parxdatenum(pds)
%   parxdatestr        - mds = parxdatestr(pds)
%   parxdump           - parxdump(info)
%   parxextractdouble  - d = parxextractdouble(info, tag)
%   parxextractmatrix  - m = parxextractmatrix(info, tag)
%   parxextractstring  - s = parxextractstring(info, tag)
%   parxextractstring2 - s = parxextractstring2(info, tag)
%   parxextractyesno   - yn = parxextractyesno(info, tag)
%   parxfilm           - f = parxfilm(imnddir)
%   parxfindseries     - serlist = parxfindseries(methname, dataroot, subdir, serlist)
%   parxfindstudies    - studylist = parxfindstudies(basedir, subdir, studylist)
%   parxindex          - : Create text index of Paravision studies
%   parxload2dseq      - [s, info, errmsg] = parxload2dseq(imnddir)
%   parxloadcsi        - [k, info] = parxloadcsi(serdir)
%   parxloadfid        - [k,info,errmsg] = parxloadfid(scandir)
%   parxloadinfo       - [info, status, errmsg] = parxloadinfo(serdir)
%   parxloadmrs        - [s, ppm, info] = parxloadmrs(imnddir)
%   parxloadmrsfid     - [k, info] = parxloadmrsfid(imnddir)
%   parxloadpc         - [fid, info] = parxloadpc(imnddir)
%   parxloadpcnav      - [k, navk, examinfo] = parxloadpcnav(imnddir, verbose)
%   parxls             - parxls(studydir)
%   parxmrsrecon       - [s,ppm,info] = parxmsrecon(scandir,zpad,lb,hamming,autophase)
%   parxplotmrs        - parxplotmrs(imnddir, ppmrange, srange)
%   parxrecon          - [s,info,errmsg] = parxrecon(sdir,options)
%   parxreport         - parxreport(basedir)
%   parxscanreport     - [reportfile,info,thumbfile] = parxscanreport(scandir,reportdir)
%   parxstudyreport    - idxfile = parxstudyreport(studydir)
%   parxstudytime      - [dt,tstart,tend] = parxstudytime(studydir)
%   parxsummary        - parxsummary(rootdir)
%   parxtextread       - lns = parxtextread(fname)
%   pvmcsiautophase    - [s_ap,phi]  = pvmcsiautophase(ppm,s,ppmA,ppmB,verbose)
%   pvmcsiphaseroll    - kr = pvmcsiphaseroll(k,info)
%   pvmcsirecon        - [s,ppm,info] = pvmcsirecon(scandir,zpad,lb,hamming,autophase)
%   pvmcsitime         - pvmcsitime(studydir,scannos)
%   pvmextractrfpulse  - rf = pvmextractrfpulse(info, tag)
%   pvmload2dseq       - [s, info, errmsg] = pvmload2dseq(scandir)
%   pvmloadfid         - [k,info,errmsg] = pvmloadfid(serdir)
%   pvmloadinfo        - [info, status, errmsg] = pvmloadinfo(serdir)
%   pvmphaseroll       - kr = pvmphaseroll(k,info)
%   pvmspatfilt        - Apply spatial filter to k-space data
